
package com.mytrip;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.airline.Flight;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TicketSearchImpl", targetNamespace = "http://mytrip.com/")
@XmlSeeAlso({
    com.airline.ObjectFactory.class,
    com.mytrip.ObjectFactory.class
})
public interface TicketSearchImpl {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<com.airline.Flight>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFlightsByDate", targetNamespace = "http://mytrip.com/", className = "com.mytrip.GetFlightsByDate")
    @ResponseWrapper(localName = "getFlightsByDateResponse", targetNamespace = "http://mytrip.com/", className = "com.mytrip.GetFlightsByDateResponse")
    @Action(input = "http://mytrip.com/TicketSearchImpl/getFlightsByDateRequest", output = "http://mytrip.com/TicketSearchImpl/getFlightsByDateResponse")
    public List<Flight> getFlightsByDate(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.airline.Flight
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLowestFareByDate", targetNamespace = "http://mytrip.com/", className = "com.mytrip.GetLowestFareByDate")
    @ResponseWrapper(localName = "getLowestFareByDateResponse", targetNamespace = "http://mytrip.com/", className = "com.mytrip.GetLowestFareByDateResponse")
    @Action(input = "http://mytrip.com/TicketSearchImpl/getLowestFareByDateRequest", output = "http://mytrip.com/TicketSearchImpl/getLowestFareByDateResponse")
    public Flight getLowestFareByDate(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
