
package com.airline;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "JetAirwaysService", targetNamespace = "http://airline.com/", wsdlLocation = "http://localhost:5001/jetairways?wsdl")
public class JetAirwaysService
    extends Service
{

    private final static URL JETAIRWAYSSERVICE_WSDL_LOCATION;
    private final static WebServiceException JETAIRWAYSSERVICE_EXCEPTION;
    private final static QName JETAIRWAYSSERVICE_QNAME = new QName("http://airline.com/", "JetAirwaysService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:5001/jetairways?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        JETAIRWAYSSERVICE_WSDL_LOCATION = url;
        JETAIRWAYSSERVICE_EXCEPTION = e;
    }

    public JetAirwaysService() {
        super(__getWsdlLocation(), JETAIRWAYSSERVICE_QNAME);
    }

    public JetAirwaysService(WebServiceFeature... features) {
        super(__getWsdlLocation(), JETAIRWAYSSERVICE_QNAME, features);
    }

    public JetAirwaysService(URL wsdlLocation) {
        super(wsdlLocation, JETAIRWAYSSERVICE_QNAME);
    }

    public JetAirwaysService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JETAIRWAYSSERVICE_QNAME, features);
    }

    public JetAirwaysService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JetAirwaysService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns JetAirways
     */
    @WebEndpoint(name = "JetAirwaysPort")
    public JetAirways getJetAirwaysPort() {
        return super.getPort(new QName("http://airline.com/", "JetAirwaysPort"), JetAirways.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JetAirways
     */
    @WebEndpoint(name = "JetAirwaysPort")
    public JetAirways getJetAirwaysPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://airline.com/", "JetAirwaysPort"), JetAirways.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JETAIRWAYSSERVICE_EXCEPTION!= null) {
            throw JETAIRWAYSSERVICE_EXCEPTION;
        }
        return JETAIRWAYSSERVICE_WSDL_LOCATION;
    }

}
