
package com.airline;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SpiceJet", targetNamespace = "http://airline.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SpiceJet {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addFlight", targetNamespace = "http://airline.com/", className = "com.airline.AddFlight")
    @ResponseWrapper(localName = "addFlightResponse", targetNamespace = "http://airline.com/", className = "com.airline.AddFlightResponse")
    @Action(input = "http://airline.com/SpiceJet/addFlightRequest", output = "http://airline.com/SpiceJet/addFlightResponse")
    public boolean addFlight(
        @WebParam(name = "arg0", targetNamespace = "")
        Flight arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkTicketAvailability", targetNamespace = "http://airline.com/", className = "com.airline.CheckTicketAvailability")
    @ResponseWrapper(localName = "checkTicketAvailabilityResponse", targetNamespace = "http://airline.com/", className = "com.airline.CheckTicketAvailabilityResponse")
    @Action(input = "http://airline.com/SpiceJet/checkTicketAvailabilityRequest", output = "http://airline.com/SpiceJet/checkTicketAvailabilityResponse")
    public int checkTicketAvailability(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFare", targetNamespace = "http://airline.com/", className = "com.airline.GetFare")
    @ResponseWrapper(localName = "getFareResponse", targetNamespace = "http://airline.com/", className = "com.airline.GetFareResponse")
    @Action(input = "http://airline.com/SpiceJet/getFareRequest", output = "http://airline.com/SpiceJet/getFareResponse")
    public int getFare(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setFlights", targetNamespace = "http://airline.com/", className = "com.airline.SetFlights")
    @ResponseWrapper(localName = "setFlightsResponse", targetNamespace = "http://airline.com/", className = "com.airline.SetFlightsResponse")
    @Action(input = "http://airline.com/SpiceJet/setFlightsRequest", output = "http://airline.com/SpiceJet/setFlightsResponse")
    public void setFlights(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Flight> arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAirlineName", targetNamespace = "http://airline.com/", className = "com.airline.GetAirlineName")
    @ResponseWrapper(localName = "getAirlineNameResponse", targetNamespace = "http://airline.com/", className = "com.airline.GetAirlineNameResponse")
    @Action(input = "http://airline.com/SpiceJet/getAirlineNameRequest", output = "http://airline.com/SpiceJet/getAirlineNameResponse")
    public String getAirlineName();

    /**
     * 
     * @return
     *     returns java.util.List<com.airline.Flight>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFlights", targetNamespace = "http://airline.com/", className = "com.airline.GetFlights")
    @ResponseWrapper(localName = "getFlightsResponse", targetNamespace = "http://airline.com/", className = "com.airline.GetFlightsResponse")
    @Action(input = "http://airline.com/SpiceJet/getFlightsRequest", output = "http://airline.com/SpiceJet/getFlightsResponse")
    public List<Flight> getFlights();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeFlight", targetNamespace = "http://airline.com/", className = "com.airline.RemoveFlight")
    @ResponseWrapper(localName = "removeFlightResponse", targetNamespace = "http://airline.com/", className = "com.airline.RemoveFlightResponse")
    @Action(input = "http://airline.com/SpiceJet/removeFlightRequest", output = "http://airline.com/SpiceJet/removeFlightResponse")
    public boolean removeFlight(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setAirlineName", targetNamespace = "http://airline.com/", className = "com.airline.SetAirlineName")
    @ResponseWrapper(localName = "setAirlineNameResponse", targetNamespace = "http://airline.com/", className = "com.airline.SetAirlineNameResponse")
    @Action(input = "http://airline.com/SpiceJet/setAirlineNameRequest", output = "http://airline.com/SpiceJet/setAirlineNameResponse")
    public void setAirlineName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
